(define (A x y)
  (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1)
                 (A x (- y 1))))))
(define (test x n)
  (cond ((> n 0) ((display (A x n))
                (display "\n")
                (test x (- n 1))))))
(test 3 3)