(define (cont-frac n d k)
  (define (cont-frac-iter i ans)
    (define (step i ans)
      (/ (n i) (+ (d i) ans)))
    (if (= i 0)
        ans
        (cont-frac-iter (- i 1) (step i ans))))
  (cont-frac-iter k 0.0))
(define (d i)
  (- (* 2 i) 1))
;; (define (test n)
;;   (define (test-iter count)
;;     (if (> count 1)
;;         (begin
;;           (display (d count))
;;           (display " ")
;;           (test-iter (- count 1)))
;;         (display (d count))))
;;   (test-iter n))
(define (tan x)
  (define (n i)
  (cond ((= i 1) x)
        ((- (* x x)))))
  (cont-frac n d 1000))
(tan 0.7853981634)
