(define (t i j)
  (cond ((= j 0) 1)
        ((= i j) 1)
        (else (+ (t (- i 1) j)
                 (t (- i 1) (- j 1))))))
(define (print n)
  (define (print-line i)
    (define (print-column j)
      (cond ((<= j i)
             (begin
               (display (t i j))
              (display " ")
              (print-column (+ j 1))))))
    (cond ((<= i n)(begin
                     (print-column 0)
                    (display "\n")
                    (print-line (+ i 1))))))
  (print-line 0))
(print 5)