(define (change amount)
  (cc amount 5))
(define (cc amount kind)
  (cond ((= amount 0) 1)
        ((< amount 0) 0)
        ((= kind 0) 0)
        (else (+ (cc (- amount
                        (getcount kind)) kind)
                 (cc amount (- kind 1))))))
(define (getcount kind)
  (cond ((= kind 1) 1)
        ((= kind 2) 5)
        ((= kind 3) 10)
        ((= kind 4) 25)
        ((= kind 5) 50)))
(display (change 200))