(define zero (lambda (f) (lambda (x) x)))
(define one (lambda (f) (lambda (x) (f x))))
(define two (lambda (f) (lambda (x) (f (f x)))))
(define (add-1 n) (lambda (f) (lambda (x) (f ((n f) x)))))
(define (my+ a b)
  (lambda (f) (lambda (x) ((a f) ((b f) x)))))
(define (f x) (+ 1 x))
((zero f) 0)
((one f) 0)
((two f) 0)
(((my+ one two) f) 0)
